on:
  schedule:
    # runs every day at 7:00 AM UTC
    - cron:  '0 7 * * *'
  # push:
    # paths:
      # - R/update_roster.R
      #- R/update-injuries.R
  workflow_dispatch:

name: update-injuries

jobs:
  update-injuries:
    name: update-injuries
    runs-on: MacOS-latest
    env:
      GITHUB_PAT: ${{ secrets.NFLVERSE_GH_TOKEN }}
      NFLDX_PASSWORD: ${{ secrets.NFLDX_PASSWORD }}
      NFLDX_USERNAME: ${{ secrets.NFLDX_USERNAME }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: | 
            nflverse/nflreadr
            nflverse/nflverse-data

      - name: Update injuries
        run: Rscript -e 'source("src/update-injuries.R")'
