on:
  schedule:
    # runs once a month
    - cron:  '0 0 1 * *'
  workflow_dispatch:

name: Update-Players

jobs:
  update-players:
    name: Update-Players
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.NFLVERSE_GH_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            nflverse/nflreadr
            nflverse/nflverse-data
            nflverse/ngsscrapR
      - name: Update players
        run: Rscript exec/update-players.R
